---
abstract: 'API Request and class generator for Apache Cloudstack'
author:
  - 'Holger Rupprecht <holger.rupprecht@gmx.de>'
build_requires:
  Test::CPAN::Changes: '0'
  Test::Exception: '0'
  Test::MockObject: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4211, CPAN::Meta::Converter version 2.150001'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojo-Cloudstack
provides:
  Mojo::Cloudstack:
    file: lib/Mojo/Cloudstack.pm
    version: '0.02'
  Mojo::Cloudstack::Api:
    file: lib/Mojo/Cloudstack/Api.pm
  Mojo::Cloudstack::Base:
    file: lib/Mojo/Cloudstack/Base.pm
requires:
  Digest::HMAC_SHA1: '1.03'
  File::HomeDir: '0'
  Mojolicious: '0'
  URI::Encode: '0'
  URL::Encode: '0'
resources:
  license: http://opensource.org/licenses/artistic-license-2.0.php
version: '0.02'
